<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Document Storage Path
    |--------------------------------------------------------------------------
    |
    | This value determines the local directory where documents will be stored
    | when using the LocalStorageDriver.
    |
    */
    'storage_path' => env('DOCUMENT_STORAGE_PATH', '/tmp/atomy/storage'),

    /*
    |--------------------------------------------------------------------------
    | URL Signature Secret
    |--------------------------------------------------------------------------
    |
    | Secret key used to sign temporary URLs generated by LocalStorageDriver.
    |
    */
    'url_secret' => env('DOCUMENT_URL_SECRET', 'change-me-to-a-secure-secret'),
];
